import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'

export const models = [
  { name: 'WIREFRAME MAN', sub: 'CYAN SCAN / SIGNAL BODY', file: '/models/wireframe_man.glb', color: 0x20d8ff, accent: 0x1565ff, mode: 'scan' },
  { name: 'HUMAN BODY WIREFRAME', sub: 'VIOLET PULSE / ANATOMY GRID', file: '/models/3d_human_body_wireframe_model.glb', color: 0xc870ff, accent: 0xff287d, mode: 'pulse' },
  { name: 'HOLOGRAMING MAN', sub: 'DATA RAIN / GHOST PROTOCOL', file: '/models/holograming_man.glb', color: 0x37f0cc, accent: 0x1e8cff, mode: 'rain' },
]
export const state = { index: 0, auto: true, current: null, loaded: false }
let scene, camera, renderer, controls, clock, root, particles, rings, scanBand, modelCache = {}
const material = (style) => new THREE.MeshPhysicalMaterial({ color: style.color, emissive: style.color, emissiveIntensity: 2.4, transparent: true, opacity: 0.52, roughness: 0.22, metalness: 0.1, transmission: 0.05, side: THREE.DoubleSide, depthWrite: false })
function buildParticles(style) { const count = style.mode === 'rain' ? 900 : style.mode === 'pulse' ? 540 : 420; const positions = new Float32Array(count*3), speeds = new Float32Array(count); for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=1.1+Math.random()*1.9; positions[i*3]=Math.cos(a)*r;positions[i*3+1]=Math.random()*3.9;positions[i*3+2]=Math.sin(a)*r*.48;speeds[i]=.2+Math.random()*.8} const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.userData.speeds=speeds;const pts=new THREE.Points(geo,new THREE.PointsMaterial({color:style.accent,size:style.mode==='rain'?.035:.055,transparent:true,opacity:.85,blending:THREE.AdditiveBlending,depthWrite:false}));pts.position.y=-.35;scene.add(pts);return pts }
function buildPlatform(style) { const group=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(2.15,2.28,.12,96),new THREE.MeshBasicMaterial({color:0x07172e,transparent:true,opacity:.92}));base.position.y=-.02;group.add(base);for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.85-i*.45,.018,8,96),new THREE.MeshBasicMaterial({color:i===0?style.color:style.accent,transparent:true,opacity:.92,blending:THREE.AdditiveBlending}));ring.rotation.x=Math.PI/2;ring.position.y=.08+i*.025;ring.userData.spin=i%2?-.5:.75;group.add(ring)}scene.add(group);return group }
function buildScan(style) { const band=new THREE.Mesh(new THREE.PlaneGeometry(4.5,.045),new THREE.MeshBasicMaterial({color:style.color,transparent:true,opacity:.72,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));band.position.y=.7;scene.add(band);return band }
async function loadModel(style) { if(modelCache[style.file]) return modelCache[style.file].clone(true);const gltf=await new GLTFLoader().loadAsync(style.file),object=gltf.scene,mat=material(style);object.traverse(c=>{if(c.isMesh){c.material=mat;c.frustumCulled=false}});const box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3()),scale=3.15/Math.max(size.x,size.y,size.z,.1);object.scale.setScalar(scale);const centered=new THREE.Box3().setFromObject(object),center=centered.getCenter(new THREE.Vector3());object.position.sub(center);object.position.y+=1.65;modelCache[style.file]=object;return object.clone(true) }
export async function showModel(index) { state.index=(index+models.length)%models.length;const style=models[state.index];document.body.dataset.mode=style.mode;if(root)scene.remove(root);root=await loadModel(style);scene.add(root);state.loaded=true;if(particles)scene.remove(particles);particles=buildParticles(style);if(rings)scene.remove(rings);rings=buildPlatform(style);if(scanBand)scene.remove(scanBand);scanBand=buildScan(style);state.current=style }
export function boot(){scene=new THREE.Scene();scene.background=new THREE.Color(0x020712);clock=new THREE.Clock();camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,100);camera.position.set(0,1.8,8.2);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;document.querySelector('#stage').appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4.3;controls.maxDistance=10;controls.target.set(0,1.55,0);scene.add(new THREE.HemisphereLight(0x6db7ff,0x01020a,1.8));const light=new THREE.PointLight(models[0].color,16,10);light.position.set(0,4,2);scene.add(light);showModel(0);animate() }
function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();if(state.auto&&root)root.rotation.y+=.0035;if(rings)rings.children.forEach(r=>{if(r.userData.spin)r.rotation.z+=r.userData.spin*.01});if(scanBand){scanBand.position.y=.25+((t*.8)%3.05);scanBand.material.opacity=.35+Math.sin(t*3)*.18}if(particles){particles.rotation.y+=.001;const pos=particles.geometry.attributes.position,speeds=particles.geometry.userData.speeds;for(let i=0;i<speeds.length;i++){let y=pos.array[i*3+1]+speeds[i]*.008;if(y>4)y=0;pos.array[i*3+1]=y}pos.needsUpdate=true}controls.update();renderer.render(scene,camera)}
