-- V001：系统表（登录账号、操作日志）。表结构见 docs/04 第三节。
-- 时间列一律 TIMESTAMP(0)，默认值 LOCALTIMESTAMP 取会话时区（后端连接时设为 Asia/Shanghai）。

CREATE TABLE SYS_USER (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY,
  USERNAME      VARCHAR2(50 CHAR)  NOT NULL,
  PASSWORD_HASH VARCHAR2(100 CHAR) NOT NULL,
  DISPLAY_NAME  VARCHAR2(50 CHAR),
  STATUS        NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT    TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  LAST_LOGIN_AT TIMESTAMP(0),
  CONSTRAINT PK_SYS_USER PRIMARY KEY (ID),
  CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN (0, 1))
);

COMMENT ON TABLE  SYS_USER               IS '登录账号';
COMMENT ON COLUMN SYS_USER.USERNAME      IS '登录名';
COMMENT ON COLUMN SYS_USER.PASSWORD_HASH IS 'BCrypt 加密后的密码';
COMMENT ON COLUMN SYS_USER.DISPLAY_NAME  IS '显示名称';
COMMENT ON COLUMN SYS_USER.STATUS        IS '1 启用，0 停用';
COMMENT ON COLUMN SYS_USER.CREATED_AT    IS '创建时间';
COMMENT ON COLUMN SYS_USER.LAST_LOGIN_AT IS '最后登录时间';

CREATE TABLE SYS_OPERATION_LOG (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY,
  USER_ID     NUMBER,
  USERNAME    VARCHAR2(50 CHAR) NOT NULL,
  ACTION      VARCHAR2(30 CHAR) NOT NULL,
  TARGET_TYPE VARCHAR2(20 CHAR) NOT NULL,
  TARGET_ID   VARCHAR2(50 CHAR) NOT NULL,
  BEFORE_JSON CLOB,
  AFTER_JSON  CLOB,
  CREATED_AT  TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_SYS_OPERATION_LOG PRIMARY KEY (ID)
);

COMMENT ON TABLE  SYS_OPERATION_LOG             IS '操作日志（只增不改，触发器 TRG_OPLOG_IMMUTABLE 拒绝修改和删除）';
COMMENT ON COLUMN SYS_OPERATION_LOG.USER_ID     IS '操作人账号 ID';
COMMENT ON COLUMN SYS_OPERATION_LOG.USERNAME    IS '操作人登录名（冗余，账号改名后日志仍可读）';
COMMENT ON COLUMN SYS_OPERATION_LOG.ACTION      IS '动作，如 STATION_PLACE、PERSON_AGE_SET';
COMMENT ON COLUMN SYS_OPERATION_LOG.TARGET_TYPE IS '对象类型，如 STATION';
COMMENT ON COLUMN SYS_OPERATION_LOG.TARGET_ID   IS '对象编号，如基站编码';
COMMENT ON COLUMN SYS_OPERATION_LOG.BEFORE_JSON IS '改动前（新增时为空）';
COMMENT ON COLUMN SYS_OPERATION_LOG.AFTER_JSON  IS '改动后（删除时为空）';
COMMENT ON COLUMN SYS_OPERATION_LOG.CREATED_AT  IS '操作时间';

-- 按对象查摆放记录（docs/05 GET /api/map/station-logs），按时间查全部日志
CREATE INDEX IX_OPLOG_TARGET ON SYS_OPERATION_LOG (TARGET_TYPE, TARGET_ID, CREATED_AT);
CREATE INDEX IX_OPLOG_TIME   ON SYS_OPERATION_LOG (CREATED_AT);

-- 修改或删除操作日志之前直接报错，让这次修改或删除作废
CREATE OR REPLACE TRIGGER TRG_OPLOG_IMMUTABLE
BEFORE UPDATE OR DELETE ON SYS_OPERATION_LOG
BEGIN
  RAISE_APPLICATION_ERROR(-20001, '操作日志不允许修改或删除');
END;
/
