-- V003：定位表（人员定位文件接入）。表结构见 docs/04 第四节，写入规则见 docs/02 第四节。
-- 每份数据记着依据哪份文件的"数据上传时间"（SRC_DATA_TIME 等），只接受时间更新的数据。

CREATE TABLE POS_INGEST_FILE (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY,
  FILE_NAME    VARCHAR2(200 CHAR) NOT NULL,
  FILE_TYPE    VARCHAR2(10 CHAR),
  MINE_CODE    VARCHAR2(12 CHAR),
  HEADER_TIME  TIMESTAMP(0),
  SHA256       CHAR(64 CHAR),
  SIZE_BYTES   NUMBER,
  STATUS       VARCHAR2(12 CHAR) NOT NULL,
  RECORD_COUNT NUMBER,
  ERROR_COUNT  NUMBER,
  ERROR_MSG    VARCHAR2(500 CHAR),
  RECEIVED_AT  TIMESTAMP(0),
  PROCESSED_AT TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  BACKUP_PATH  VARCHAR2(500 CHAR),
  CONSTRAINT PK_POS_INGEST_FILE PRIMARY KEY (ID),
  CONSTRAINT CK_POS_INGEST_FILE_STATUS
    CHECK (STATUS IN ('DONE', 'PARTIAL', 'FAILED', 'STALE', 'DUPLICATE', 'UNKNOWN'))
);

COMMENT ON TABLE  POS_INGEST_FILE              IS '每个定位文件的处理记录';
COMMENT ON COLUMN POS_INGEST_FILE.FILE_NAME    IS '文件名（不含目录）';
COMMENT ON COLUMN POS_INGEST_FILE.FILE_TYPE    IS '文件类型，如 RYSS；文件名不合法时为空';
COMMENT ON COLUMN POS_INGEST_FILE.MINE_CODE    IS '煤矿编码（来自文件名）';
COMMENT ON COLUMN POS_INGEST_FILE.HEADER_TIME  IS '文件头里的数据上传时间，判断新旧的依据；没解析到时为空';
COMMENT ON COLUMN POS_INGEST_FILE.SHA256       IS '内容摘要，用来去重；没读取内容（如符号链接）时为空';
COMMENT ON COLUMN POS_INGEST_FILE.SIZE_BYTES   IS '文件大小（字节）';
COMMENT ON COLUMN POS_INGEST_FILE.STATUS       IS 'DONE 成功 / PARTIAL 部分记录失败 / FAILED 失败 / STALE 过期未生效 / DUPLICATE 重复 / UNKNOWN 未识别类型';
COMMENT ON COLUMN POS_INGEST_FILE.RECORD_COUNT IS '成功入库的记录数';
COMMENT ON COLUMN POS_INGEST_FILE.ERROR_COUNT  IS '出错的记录数（不含警告）';
COMMENT ON COLUMN POS_INGEST_FILE.ERROR_MSG    IS '失败原因或部分成功的说明';
COMMENT ON COLUMN POS_INGEST_FILE.RECEIVED_AT  IS '文件在收件箱里的最后修改时间';
COMMENT ON COLUMN POS_INGEST_FILE.PROCESSED_AT IS '处理时间';
COMMENT ON COLUMN POS_INGEST_FILE.BACKUP_PATH  IS '备份或失败目录里的位置（相对于对应目录）';

-- 查重复：同名同摘要；不设唯一，重复的文件也要记一行 DUPLICATE
CREATE INDEX IX_POS_FILE_NAME_SHA ON POS_INGEST_FILE (FILE_NAME, SHA256);
-- 按类型找最新一份生效的文件（V_POS_IN_WELL、状态接口）：带上状态列，只读索引就能取到最大时间，不用回表
CREATE INDEX IX_POS_FILE_TYPE_TIME ON POS_INGEST_FILE (FILE_TYPE, STATUS, HEADER_TIME);

CREATE TABLE POS_INGEST_ERROR (
  ID       NUMBER GENERATED ALWAYS AS IDENTITY,
  FILE_ID  NUMBER NOT NULL,
  KIND     VARCHAR2(10 CHAR) NOT NULL,
  LINE_NO  NUMBER NOT NULL,
  RAW_TEXT VARCHAR2(1000 CHAR),
  REASON   VARCHAR2(200 CHAR) NOT NULL,
  CONSTRAINT PK_POS_INGEST_ERROR PRIMARY KEY (ID),
  CONSTRAINT FK_POS_INGEST_ERROR_FILE FOREIGN KEY (FILE_ID) REFERENCES POS_INGEST_FILE (ID),
  CONSTRAINT CK_POS_INGEST_ERROR_KIND CHECK (KIND IN ('ERROR', 'WARN'))
);

COMMENT ON TABLE  POS_INGEST_ERROR          IS '定位文件里有问题的记录（仅供运维排查，页面不展示）';
COMMENT ON COLUMN POS_INGEST_ERROR.KIND     IS 'ERROR 记录被跳过 / WARN 记录已入库但需要人工核对（如同一文件里卡编码重复）';
COMMENT ON COLUMN POS_INGEST_ERROR.LINE_NO  IS '第几条记录（文件头之后从 1 数起）';
COMMENT ON COLUMN POS_INGEST_ERROR.RAW_TEXT IS '记录原文，超长截断；含姓名，页面不展示';
COMMENT ON COLUMN POS_INGEST_ERROR.REASON   IS '原因';

CREATE INDEX IX_POS_ERROR_FILE ON POS_INGEST_ERROR (FILE_ID);

CREATE TABLE POS_AREA (
  AREA_CODE     VARCHAR2(16 CHAR) NOT NULL,
  AREA_TYPE     VARCHAR2(10 CHAR),
  AREA_NAME     VARCHAR2(100 CHAR),
  QUOTA         NUMBER(6),
  SRC_DATA_TIME TIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_POS_AREA PRIMARY KEY (AREA_CODE)
);

COMMENT ON TABLE  POS_AREA               IS '区域（来自 RYQY）';
COMMENT ON COLUMN POS_AREA.AREA_TYPE     IS '原值：井口区域 / 重点区域 / 限制区域 / 其它区域';
COMMENT ON COLUMN POS_AREA.AREA_NAME     IS '区域名称，如 -750大巷';
COMMENT ON COLUMN POS_AREA.QUOTA         IS '核定人数';
COMMENT ON COLUMN POS_AREA.SRC_DATA_TIME IS '依据的 RYQY 文件上传时间';

CREATE TABLE POS_STATION (
  STATION_CODE    VARCHAR2(22 CHAR) NOT NULL,
  AREA_CODE       VARCHAR2(16 CHAR) GENERATED ALWAYS AS (SUBSTR(STATION_CODE, 1, 16)) VIRTUAL,
  STATION_NAME    VARCHAR2(200 CHAR),
  RUN_STATUS      NUMBER(1),
  POWER_STATUS    NUMBER(1),
  STATUS_TIME     TIMESTAMP(0),
  NAME_SRC_TIME   TIMESTAMP(0),
  STATUS_SRC_TIME TIMESTAMP(0),
  CONSTRAINT PK_POS_STATION PRIMARY KEY (STATION_CODE),
  CONSTRAINT CK_POS_STATION_RUN CHECK (RUN_STATUS IN (0, 1, 2, 9)),
  CONSTRAINT CK_POS_STATION_POWER CHECK (POWER_STATUS IN (0, 1, 2, 9))
);

COMMENT ON TABLE  POS_STATION                 IS '基站（名称来自 RYJZ，运行状态来自 JZSS）';
COMMENT ON COLUMN POS_STATION.AREA_CODE       IS '所属区域，基站编码前 16 位（虚拟列）';
COMMENT ON COLUMN POS_STATION.STATION_NAME    IS '厂家名称，可为空';
COMMENT ON COLUMN POS_STATION.RUN_STATUS      IS '0 通讯正常、1 通讯中断、2 故障、9 未知';
COMMENT ON COLUMN POS_STATION.POWER_STATUS    IS '0 直流、1 交流、2 电源故障、9 未知';
COMMENT ON COLUMN POS_STATION.STATUS_TIME     IS '运行状态的数据时间（JZSS 记录里的时间）';
COMMENT ON COLUMN POS_STATION.NAME_SRC_TIME   IS '名称依据的 RYJZ 文件上传时间';
COMMENT ON COLUMN POS_STATION.STATUS_SRC_TIME IS '状态依据的 JZSS 文件上传时间';

CREATE INDEX IX_POS_STATION_AREA ON POS_STATION (AREA_CODE);

CREATE TABLE POS_STATION_MARK (
  STATION_CODE VARCHAR2(22 CHAR) NOT NULL,
  DISPLAY_NAME VARCHAR2(200 CHAR),
  X            NUMBER(15,3) NOT NULL,
  Y            NUMBER(15,3) NOT NULL,
  PLACED_BY    VARCHAR2(50 CHAR) NOT NULL,
  PLACED_AT    TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  UPDATED_BY   VARCHAR2(50 CHAR),
  UPDATED_AT   TIMESTAMP(0),
  VERSION      NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT PK_POS_STATION_MARK PRIMARY KEY (STATION_CODE)
);

COMMENT ON TABLE  POS_STATION_MARK              IS '基站在地图上的位置（人工摆放，不设外键：允许先摆放后收到文件）';
COMMENT ON COLUMN POS_STATION_MARK.DISPLAY_NAME IS '用户起的名字，优先于厂家名称';
COMMENT ON COLUMN POS_STATION_MARK.X            IS '地图坐标 X（EPSG:4527，见 docs/06）';
COMMENT ON COLUMN POS_STATION_MARK.Y            IS '地图坐标 Y（EPSG:4527，见 docs/06）';
COMMENT ON COLUMN POS_STATION_MARK.PLACED_BY    IS '首次摆放人（登录名）';
COMMENT ON COLUMN POS_STATION_MARK.UPDATED_BY   IS '最后修改人（登录名）';
COMMENT ON COLUMN POS_STATION_MARK.VERSION      IS '乐观锁版本号：两人同时改，后提交的收到冲突提示';

CREATE TABLE POS_PERSON (
  CARD_CODE      VARCHAR2(17 CHAR) NOT NULL,
  PERSON_NAME    VARCHAR2(50 CHAR),
  JOB_KIND       VARCHAR2(50 CHAR),
  JOB_TITLE      VARCHAR2(50 CHAR),
  DEPT           VARCHAR2(100 CHAR),
  IS_LEADER      NUMBER(1),
  IS_SPECIAL     NUMBER(1),
  AGE            NUMBER(3),
  AGE_UPDATED_BY VARCHAR2(50 CHAR),
  AGE_UPDATED_AT TIMESTAMP(0),
  FROM_RYXX      NUMBER(1) NOT NULL,
  SRC_DATA_TIME  TIMESTAMP(0) NOT NULL,
  CREATED_AT     TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  UPDATED_AT     TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_POS_PERSON PRIMARY KEY (CARD_CODE),
  CONSTRAINT CK_POS_PERSON_FROM CHECK (FROM_RYXX IN (0, 1)),
  CONSTRAINT CK_POS_PERSON_AGE CHECK (AGE BETWEEN 0 AND 150)
);

COMMENT ON TABLE  POS_PERSON                IS '人员基本信息（厂家字段只读，年龄人工录入）';
COMMENT ON COLUMN POS_PERSON.CARD_CODE      IS '人员卡编码（17 位），人员唯一 ID';
COMMENT ON COLUMN POS_PERSON.PERSON_NAME    IS '姓名（厂家）';
COMMENT ON COLUMN POS_PERSON.JOB_KIND       IS '工种（厂家；"未设置"存 NULL）';
COMMENT ON COLUMN POS_PERSON.JOB_TITLE      IS '职务（厂家；"未设置"存 NULL）';
COMMENT ON COLUMN POS_PERSON.DEPT           IS '队组/部门（厂家，原样）';
COMMENT ON COLUMN POS_PERSON.IS_LEADER      IS '是否矿领导，1 是';
COMMENT ON COLUMN POS_PERSON.IS_SPECIAL     IS '是否特种人员，1 是';
COMMENT ON COLUMN POS_PERSON.AGE            IS '年龄，人工录入；为空显示"未录入"';
COMMENT ON COLUMN POS_PERSON.FROM_RYXX      IS '1 来自 RYXX；0 只是从 RYSS 补录的（缺工种、部门）';
COMMENT ON COLUMN POS_PERSON.SRC_DATA_TIME  IS '厂家字段依据的文件上传时间';

CREATE INDEX IX_POS_PERSON_DEPT ON POS_PERSON (DEPT);
CREATE INDEX IX_POS_PERSON_JOB  ON POS_PERSON (JOB_KIND);
CREATE INDEX IX_POS_PERSON_NAME ON POS_PERSON (PERSON_NAME);

CREATE TABLE POS_PERSON_STATE (
  CARD_CODE          VARCHAR2(17 CHAR) NOT NULL,
  IN_OUT_FLAG        NUMBER(1) NOT NULL,
  IN_TIME            TIMESTAMP(0),
  OUT_TIME           TIMESTAMP(0),
  AREA_CODE          VARCHAR2(16 CHAR),
  AREA_ENTER_TIME    TIMESTAMP(0),
  STATION_CODE       VARCHAR2(22 CHAR),
  STATION_ENTER_TIME TIMESTAMP(0),
  DISTANCE_M         NUMBER(8,2),
  SHIFT_MODE         VARCHAR2(20 CHAR),
  WORK_STATUS        VARCHAR2(10 CHAR),
  SRC_DATA_TIME      TIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_POS_PERSON_STATE PRIMARY KEY (CARD_CODE),
  CONSTRAINT CK_POS_PERSON_STATE_FLAG CHECK (IN_OUT_FLAG IN (0, 1, 2))
);

COMMENT ON TABLE  POS_PERSON_STATE                    IS '人员当前位置与出入井状态（来自 RYSS）';
COMMENT ON COLUMN POS_PERSON_STATE.IN_OUT_FLAG        IS '0 井口、1 已入井、2 已出井';
COMMENT ON COLUMN POS_PERSON_STATE.STATION_CODE       IS '当前基站（离他最近的）';
COMMENT ON COLUMN POS_PERSON_STATE.DISTANCE_M         IS '距基站距离（米，有正负），仅参考';
COMMENT ON COLUMN POS_PERSON_STATE.SHIFT_MODE         IS '劳动组织方式，如三八制';
COMMENT ON COLUMN POS_PERSON_STATE.WORK_STATUS        IS '正常 / 求救';
COMMENT ON COLUMN POS_PERSON_STATE.SRC_DATA_TIME      IS '依据哪份 RYSS（那份文件的上传时间）';

CREATE INDEX IX_POS_STATE_SRC_TIME ON POS_PERSON_STATE (SRC_DATA_TIME);
CREATE INDEX IX_POS_STATE_STATION  ON POS_PERSON_STATE (STATION_CODE);

-- 全系统统一的"井下人数"口径：最新一份生效的 RYSS 里出入井标志为 1 的人
CREATE OR REPLACE VIEW V_POS_IN_WELL AS
SELECT s.*
  FROM POS_PERSON_STATE s
 WHERE s.IN_OUT_FLAG = 1
   AND s.SRC_DATA_TIME = (SELECT MAX(HEADER_TIME) FROM POS_INGEST_FILE
                           WHERE FILE_TYPE = 'RYSS' AND STATUS IN ('DONE', 'PARTIAL'));

CREATE TABLE POS_PRESENCE_DAILY (
  STAT_DATE      DATE NOT NULL,
  CARD_CODE      VARCHAR2(17 CHAR) NOT NULL,
  FIRST_IN_TIME  TIMESTAMP(0),
  LAST_OUT_TIME  TIMESTAMP(0),
  LAST_SEEN_TIME TIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_POS_PRESENCE_DAILY PRIMARY KEY (STAT_DATE, CARD_CODE)
);

COMMENT ON TABLE  POS_PRESENCE_DAILY                IS '每人每天的入井/出井记录（按 RYSS 快照日期，跨零点的夜班两天各一行）';
COMMENT ON COLUMN POS_PRESENCE_DAILY.STAT_DATE      IS 'RYSS 文件头时间的日期';
COMMENT ON COLUMN POS_PRESENCE_DAILY.FIRST_IN_TIME  IS '最早入井时刻（可能是前一天）';
COMMENT ON COLUMN POS_PRESENCE_DAILY.LAST_OUT_TIME  IS '最晚出井时刻';
COMMENT ON COLUMN POS_PRESENCE_DAILY.LAST_SEEN_TIME IS '当天最后一次以"已入井"出现在快照里的快照时间';

CREATE INDEX IX_POS_PRESENCE_CARD ON POS_PRESENCE_DAILY (CARD_CODE, STAT_DATE);

CREATE TABLE POS_HEADCOUNT_SERIES (
  SNAPSHOT_TIME TIMESTAMP(0) NOT NULL,
  IN_WELL_COUNT NUMBER(6) NOT NULL,
  OUT_COUNT     NUMBER(6) NOT NULL,
  TOTAL_COUNT   NUMBER(6) NOT NULL,
  CONSTRAINT PK_POS_HEADCOUNT_SERIES PRIMARY KEY (SNAPSHOT_TIME)
);

COMMENT ON TABLE  POS_HEADCOUNT_SERIES               IS '井下人数随时间变化（每份 RYSS 一个点）';
COMMENT ON COLUMN POS_HEADCOUNT_SERIES.SNAPSHOT_TIME IS 'RYSS 文件头的上传时间';
COMMENT ON COLUMN POS_HEADCOUNT_SERIES.IN_WELL_COUNT IS '出入井标志为 1 的人数';
COMMENT ON COLUMN POS_HEADCOUNT_SERIES.OUT_COUNT     IS '出入井标志为 2 的人数';
COMMENT ON COLUMN POS_HEADCOUNT_SERIES.TOTAL_COUNT   IS '这份快照里成功入库的总人数';
