-- V004：手表与体征表。表结构见 docs/04 第五节，写入规则见 docs/03 第五节。
-- 手表数据先进 Redis 缓冲，再成批写进这些表；每一步写入都可以重复执行而结果不变
-- （流水按 MSG_ID 去重，最新值、步数、在线时间只接受更新的时间）。

CREATE TABLE DEVICE (
  IMEI          VARCHAR2(15 CHAR) NOT NULL,
  CARD_CODE     VARCHAR2(17 CHAR),
  MODEL         VARCHAR2(50 CHAR),
  BOUND_AT      TIMESTAMP(0),
  LAST_SEEN_AT  TIMESTAMP(0),
  BATTERY_PCT   NUMBER(3),
  BATTERY_TIME  TIMESTAMP(0),
  STATUS        NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DEVICE PRIMARY KEY (IMEI),
  CONSTRAINT UK_DEVICE_CARD UNIQUE (CARD_CODE),
  CONSTRAINT FK_DEVICE_PERSON FOREIGN KEY (CARD_CODE) REFERENCES POS_PERSON (CARD_CODE),
  CONSTRAINT CK_DEVICE_IMEI CHECK (REGEXP_LIKE(IMEI, '^[0-9]{15}$')),
  CONSTRAINT CK_DEVICE_BATTERY CHECK (BATTERY_PCT BETWEEN 1 AND 100),
  CONSTRAINT CK_DEVICE_STATUS CHECK (STATUS IN (0, 1))
);

COMMENT ON TABLE  DEVICE              IS '手表，与人员绑定（一块表绑一个人，一个人绑一块表）';
COMMENT ON COLUMN DEVICE.IMEI         IS '设备号，15 位数字';
COMMENT ON COLUMN DEVICE.CARD_CODE    IS '绑定的人员卡编码；为空表示已登记、未绑定';
COMMENT ON COLUMN DEVICE.MODEL        IS '型号';
COMMENT ON COLUMN DEVICE.BOUND_AT     IS '绑定时间';
COMMENT ON COLUMN DEVICE.LAST_SEEN_AT IS '最后一次收到任何上行包的时间，决定是否在线；只接受更晚的时间';
COMMENT ON COLUMN DEVICE.BATTERY_PCT  IS '最新电量（%），只来自心跳 AP03；0 不覆盖已有值';
COMMENT ON COLUMN DEVICE.BATTERY_TIME IS '电量的收到时间';
COMMENT ON COLUMN DEVICE.STATUS       IS '1 启用 / 0 停用（停用的表按未登记处理）';

-- 体征流水：一行一个指标。按月自动建分区，保留 12 个月（docs/04）
CREATE TABLE HEALTH_RECORD (
  MSG_ID       NUMBER(19)        NOT NULL,
  CARD_CODE    VARCHAR2(17 CHAR) NOT NULL,
  METRIC       VARCHAR2(20 CHAR) NOT NULL,
  VAL1         NUMBER(6,1)       NOT NULL,
  VAL2         NUMBER(6,1),
  COLLECTED_AT TIMESTAMP(0)      NOT NULL,
  DEVICE_IMEI  VARCHAR2(15 CHAR),
  CONSTRAINT CK_HR_METRIC CHECK (METRIC IN ('HEART_RATE', 'SPO2', 'TEMPERATURE', 'BLOOD_PRESSURE'))
)
PARTITION BY RANGE (COLLECTED_AT) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(PARTITION P_BEFORE VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'));

COMMENT ON TABLE  HEALTH_RECORD              IS '体征流水（月分区），一行一个指标';
COMMENT ON COLUMN HEALTH_RECORD.MSG_ID       IS '收到时生成的唯一编号，重试时防止重复入库';
COMMENT ON COLUMN HEALTH_RECORD.CARD_CODE    IS '收到时手表绑定的人员卡编码，之后不再改';
COMMENT ON COLUMN HEALTH_RECORD.METRIC       IS 'HEART_RATE 心率 / SPO2 血氧 / TEMPERATURE 体温 / BLOOD_PRESSURE 血压';
COMMENT ON COLUMN HEALTH_RECORD.VAL1         IS '主值；血压时是收缩压';
COMMENT ON COLUMN HEALTH_RECORD.VAL2         IS '仅血压：舒张压';
COMMENT ON COLUMN HEALTH_RECORD.COLLECTED_AT IS '采集时间（服务器收到的时间，手表体征包不带时间）';
COMMENT ON COLUMN HEALTH_RECORD.DEVICE_IMEI  IS '上传的手表';

-- 某人某指标的趋势、某人某天有没有数据
CREATE INDEX IX_HR_CARD_METRIC_TIME ON HEALTH_RECORD (CARD_CODE, METRIC, COLLECTED_AT) LOCAL;
-- 日汇总只读"今天"的数据
CREATE INDEX IX_HR_TIME ON HEALTH_RECORD (COLLECTED_AT) LOCAL;
-- 同一条数据写两次时第二次被跳过；分区表的唯一本地索引必须包含分区列
CREATE UNIQUE INDEX UX_HR_MSG ON HEALTH_RECORD (MSG_ID, COLLECTED_AT) LOCAL;

CREATE TABLE HEALTH_LATEST (
  CARD_CODE    VARCHAR2(17 CHAR) NOT NULL,
  METRIC       VARCHAR2(20 CHAR) NOT NULL,
  VAL1         NUMBER(6,1)       NOT NULL,
  VAL2         NUMBER(6,1),
  COLLECTED_AT TIMESTAMP(0)      NOT NULL,
  MSG_ID       NUMBER(19)        NOT NULL,
  DEVICE_IMEI  VARCHAR2(15 CHAR),
  CONSTRAINT PK_HEALTH_LATEST PRIMARY KEY (CARD_CODE, METRIC),
  CONSTRAINT CK_HL_METRIC CHECK (METRIC IN ('HEART_RATE', 'SPO2', 'TEMPERATURE', 'BLOOD_PRESSURE'))
);

COMMENT ON TABLE  HEALTH_LATEST              IS '每人每指标的最新值（大屏、地图弹窗直接查它）';
COMMENT ON COLUMN HEALTH_LATEST.COLLECTED_AT IS '采集时间；只接受更晚的数据';
COMMENT ON COLUMN HEALTH_LATEST.MSG_ID       IS '这条值的流水编号；采集时间同一秒时，编号大的算新';

CREATE TABLE HEALTH_DAILY_SUMMARY (
  STAT_DATE    DATE              NOT NULL,
  CARD_CODE    VARCHAR2(17 CHAR) NOT NULL,
  METRIC       VARCHAR2(20 CHAR) NOT NULL,
  MAX_V        NUMBER(6,1)       NOT NULL,
  MIN_V        NUMBER(6,1)       NOT NULL,
  AVG_V        NUMBER(7,2)       NOT NULL,
  SAMPLE_COUNT NUMBER(8)         NOT NULL,
  NORMAL_COUNT NUMBER(8)         NOT NULL,
  RULE_GROUP   VARCHAR2(20 CHAR) NOT NULL,
  UPDATED_AT   TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_HEALTH_DAILY_SUMMARY PRIMARY KEY (STAT_DATE, CARD_CODE, METRIC),
  CONSTRAINT CK_HDS_METRIC CHECK (METRIC IN ('HEART_RATE', 'SPO2', 'TEMPERATURE', 'BP_SYS', 'BP_DIA'))
);

COMMENT ON TABLE  HEALTH_DAILY_SUMMARY              IS '每人每天每指标的统计（每 5 分钟重算今天，0:10 定稿昨天）';
COMMENT ON COLUMN HEALTH_DAILY_SUMMARY.METRIC       IS 'HEART_RATE / SPO2 / TEMPERATURE / BP_SYS 收缩压 / BP_DIA 舒张压';
COMMENT ON COLUMN HEALTH_DAILY_SUMMARY.SAMPLE_COUNT IS '当天有效样本数';
COMMENT ON COLUMN HEALTH_DAILY_SUMMARY.NORMAL_COUNT IS '落在正常范围内的样本数（按这个人所属岗位类别在统计当时的阈值）';
COMMENT ON COLUMN HEALTH_DAILY_SUMMARY.RULE_GROUP   IS '算 NORMAL_COUNT 时用的岗位类别';

CREATE INDEX IX_HDS_CARD ON HEALTH_DAILY_SUMMARY (CARD_CODE, STAT_DATE);

CREATE TABLE STEP_DAILY (
  STAT_DATE   DATE              NOT NULL,
  CARD_CODE   VARCHAR2(17 CHAR) NOT NULL,
  STEPS       NUMBER(8)         NOT NULL,
  LAST_RAW    NUMBER(10)        NOT NULL,
  UPDATED_AT  TIMESTAMP(3)      NOT NULL,
  DEVICE_IMEI VARCHAR2(15 CHAR) NOT NULL,
  CONSTRAINT PK_STEP_DAILY PRIMARY KEY (STAT_DATE, CARD_CODE),
  CONSTRAINT CK_STEP_DAILY_STEPS CHECK (STEPS >= 0)
);

COMMENT ON TABLE  STEP_DAILY             IS '每人每天步数；写入是覆盖（只接受更晚的读数），不是累加';
COMMENT ON COLUMN STEP_DAILY.STEPS       IS '当天累计步数（各次计数器读数的增量之和，docs/03 第五节）';
COMMENT ON COLUMN STEP_DAILY.LAST_RAW    IS '最近一次手表计数器读数';
COMMENT ON COLUMN STEP_DAILY.UPDATED_AT  IS '这次读数的收到时间（毫秒，用来判断读数先后）';
COMMENT ON COLUMN STEP_DAILY.DEVICE_IMEI IS 'LAST_RAW 来自哪块表；换表后旧表的读数不能作为新表的起点';

CREATE INDEX IX_STEP_DAILY_CARD ON STEP_DAILY (CARD_CODE, STAT_DATE);

CREATE TABLE METRIC_COUNTER (
  METRIC      VARCHAR2(20 CHAR) NOT NULL,
  TOTAL_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_METRIC_COUNTER PRIMARY KEY (METRIC)
);

COMMENT ON TABLE  METRIC_COUNTER             IS '累计采集条数；每批写库时在同一个事务里加上真正新插入的条数';
COMMENT ON COLUMN METRIC_COUNTER.TOTAL_COUNT IS '大屏"累计采集数据"取四行之和';

INSERT INTO METRIC_COUNTER (METRIC, TOTAL_COUNT) VALUES ('HEART_RATE', 0);
INSERT INTO METRIC_COUNTER (METRIC, TOTAL_COUNT) VALUES ('SPO2', 0);
INSERT INTO METRIC_COUNTER (METRIC, TOTAL_COUNT) VALUES ('TEMPERATURE', 0);
INSERT INTO METRIC_COUNTER (METRIC, TOTAL_COUNT) VALUES ('BLOOD_PRESSURE', 0);
