-- V005：岗位类别、预警阈值、预警事件、关注名单。表结构见 docs/04 第六节，预警规则见 docs/03 第四节。
-- 告警是"发生过"的记录，只用来展示和统计，没有处置状态。

CREATE TABLE JOB_GROUP (
  GROUP_CODE       VARCHAR2(20 CHAR) NOT NULL,
  GROUP_NAME       VARCHAR2(50 CHAR) NOT NULL,
  SORT_NO          NUMBER(4) DEFAULT 0 NOT NULL,
  MIN_EVAL_DAYS    NUMBER(3),
  RISK_EVENT_COUNT NUMBER(4),
  CONSTRAINT PK_JOB_GROUP PRIMARY KEY (GROUP_CODE)
);

COMMENT ON TABLE  JOB_GROUP                  IS '岗位类别；每类一套预警阈值。DEFAULT 不能删除';
COMMENT ON COLUMN JOB_GROUP.MIN_EVAL_DAYS    IS '月报：某指标有数据的天数少于它，不参与稳定性评估；空则用 DEFAULT 的';
COMMENT ON COLUMN JOB_GROUP.RISK_EVENT_COUNT IS '月报：一个月里六类告警事件达到它，列为风险职工；空则用 DEFAULT 的';

INSERT INTO JOB_GROUP (GROUP_CODE, GROUP_NAME, SORT_NO, MIN_EVAL_DAYS, RISK_EVENT_COUNT)
VALUES ('DEFAULT', '默认', 0, 5, 3);

-- DEFAULT 不能删除：工种没归类、工种为空时都按它判断
CREATE OR REPLACE TRIGGER TRG_JOB_GROUP_KEEP_DEFAULT
BEFORE DELETE ON JOB_GROUP
FOR EACH ROW
WHEN (OLD.GROUP_CODE = 'DEFAULT')
BEGIN
  RAISE_APPLICATION_ERROR(-20002, '默认岗位类别 DEFAULT 不能删除');
END;
/

CREATE TABLE JOB_KIND_GROUP (
  JOB_KIND   VARCHAR2(50 CHAR) NOT NULL,
  GROUP_CODE VARCHAR2(20 CHAR) NOT NULL,
  UPDATED_BY VARCHAR2(50 CHAR),
  UPDATED_AT TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_JOB_KIND_GROUP PRIMARY KEY (JOB_KIND),
  CONSTRAINT FK_JOB_KIND_GROUP FOREIGN KEY (GROUP_CODE) REFERENCES JOB_GROUP (GROUP_CODE)
);

COMMENT ON TABLE  JOB_KIND_GROUP          IS '工种归到哪个岗位类别；表里没有的工种都算 DEFAULT';
COMMENT ON COLUMN JOB_KIND_GROUP.JOB_KIND IS '工种，和 POS_PERSON.JOB_KIND 的原值一致';

CREATE TABLE ALERT_RULE (
  GROUP_CODE   VARCHAR2(20 CHAR) NOT NULL,
  METRIC       VARCHAR2(20 CHAR) NOT NULL,
  LOW_LIMIT    NUMBER(6,1),
  HIGH_LIMIT   NUMBER(6,1),
  SEVERITY     NUMBER(1) DEFAULT 2 NOT NULL,
  ENABLED      NUMBER(1) DEFAULT 1 NOT NULL,
  STABLE_PCT   NUMBER(5,2),
  UNSTABLE_PCT NUMBER(5,2),
  UPDATED_AT   TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  UPDATED_BY   VARCHAR2(50 CHAR),
  CONSTRAINT PK_ALERT_RULE PRIMARY KEY (GROUP_CODE, METRIC),
  CONSTRAINT FK_ALERT_RULE_GROUP FOREIGN KEY (GROUP_CODE) REFERENCES JOB_GROUP (GROUP_CODE),
  CONSTRAINT CK_ALERT_RULE_METRIC CHECK (METRIC IN ('HEART_RATE', 'SPO2', 'TEMPERATURE', 'BP_SYS', 'BP_DIA')),
  CONSTRAINT CK_ALERT_RULE_SEVERITY CHECK (SEVERITY IN (1, 2, 3)),
  CONSTRAINT CK_ALERT_RULE_ENABLED CHECK (ENABLED IN (0, 1)),
  CONSTRAINT CK_ALERT_RULE_LIMITS CHECK (LOW_LIMIT IS NULL OR HIGH_LIMIT IS NULL OR LOW_LIMIT < HIGH_LIMIT)
);

COMMENT ON TABLE  ALERT_RULE              IS '各岗位类别的预警阈值；某类别缺哪一行就用 DEFAULT 的那一行';
COMMENT ON COLUMN ALERT_RULE.LOW_LIMIT    IS '低于它算偏低；空则不判断偏低';
COMMENT ON COLUMN ALERT_RULE.HIGH_LIMIT   IS '高于它算偏高；空则不判断偏高';
COMMENT ON COLUMN ALERT_RULE.SEVERITY     IS '事件严重程度：1 提示 / 2 一般 / 3 严重';
COMMENT ON COLUMN ALERT_RULE.ENABLED      IS '1 启用 / 0 停用（停用时不产生事件，日汇总也不判异常）';
COMMENT ON COLUMN ALERT_RULE.STABLE_PCT   IS '月报：正常率达到它算稳定；空则用 DEFAULT 的';
COMMENT ON COLUMN ALERT_RULE.UNSTABLE_PCT IS '月报：正常率低于它算不稳定；空则用 DEFAULT 的';

-- DEFAULT 类别的初始值是开发占位值，上线前请矿上医务人员确定（docs/00 第 3、22 项）
INSERT INTO ALERT_RULE (GROUP_CODE, METRIC, LOW_LIMIT, HIGH_LIMIT, STABLE_PCT, UNSTABLE_PCT)
VALUES ('DEFAULT', 'HEART_RATE', 50, 120, 90, 70);
INSERT INTO ALERT_RULE (GROUP_CODE, METRIC, LOW_LIMIT, HIGH_LIMIT, STABLE_PCT, UNSTABLE_PCT)
VALUES ('DEFAULT', 'SPO2', 90, NULL, 90, 70);
INSERT INTO ALERT_RULE (GROUP_CODE, METRIC, LOW_LIMIT, HIGH_LIMIT, STABLE_PCT, UNSTABLE_PCT)
VALUES ('DEFAULT', 'TEMPERATURE', 35.0, 37.3, 90, 70);
INSERT INTO ALERT_RULE (GROUP_CODE, METRIC, LOW_LIMIT, HIGH_LIMIT, STABLE_PCT, UNSTABLE_PCT)
VALUES ('DEFAULT', 'BP_SYS', 90, 140, 90, 70);
INSERT INTO ALERT_RULE (GROUP_CODE, METRIC, LOW_LIMIT, HIGH_LIMIT, STABLE_PCT, UNSTABLE_PCT)
VALUES ('DEFAULT', 'BP_DIA', 60, 90, 90, 70);

CREATE TABLE ALERT_EVENT (
  ID               NUMBER GENERATED ALWAYS AS IDENTITY,
  CARD_CODE        VARCHAR2(17 CHAR),
  SRC              VARCHAR2(10 CHAR) NOT NULL,
  CODE             VARCHAR2(20 CHAR) NOT NULL,
  CATEGORY         VARCHAR2(20 CHAR) NOT NULL,
  SEVERITY         NUMBER(1) NOT NULL,
  VAL_TEXT         VARCHAR2(50 CHAR),
  RULE_GROUP       VARCHAR2(20 CHAR),
  OCCURRED_AT      TIMESTAMP(0) NOT NULL,
  LAST_OCCURRED_AT TIMESTAMP(0) NOT NULL,
  OCCUR_COUNT      NUMBER(6) DEFAULT 1 NOT NULL,
  DEVICE_IMEI      VARCHAR2(15 CHAR),
  CONSTRAINT PK_ALERT_EVENT PRIMARY KEY (ID),
  CONSTRAINT CK_ALERT_EVENT_SRC CHECK (SRC IN ('THRESHOLD', 'DEVICE')),
  CONSTRAINT CK_ALERT_EVENT_CATEGORY
    CHECK (CATEGORY IN ('SOS', 'FALL', 'HEART_RATE', 'BLOOD_PRESSURE', 'SPO2', 'TEMPERATURE', 'OTHER')),
  CONSTRAINT CK_ALERT_EVENT_SEVERITY CHECK (SEVERITY IN (1, 2, 3)),
  -- 没有卡编码时必须有设备号，否则无法区分是谁
  CONSTRAINT CK_ALERT_EVENT_WHO CHECK (CARD_CODE IS NOT NULL OR DEVICE_IMEI IS NOT NULL),
  -- 一条事件不跨天（docs/03 第四节）
  CONSTRAINT CK_ALERT_EVENT_SAME_DAY
    CHECK (TRUNC(LAST_OCCURRED_AT) = TRUNC(OCCURRED_AT) AND LAST_OCCURRED_AT >= OCCURRED_AT)
);

COMMENT ON TABLE  ALERT_EVENT                  IS '预警事件（发生过的记录，没有处置状态）';
COMMENT ON COLUMN ALERT_EVENT.CARD_CODE        IS '可空：手表未登记或未绑定时为空，此时按 DEVICE_IMEI 区分';
COMMENT ON COLUMN ALERT_EVENT.SRC              IS 'THRESHOLD 体征越界 / DEVICE 设备报警（手表 AP10）';
COMMENT ON COLUMN ALERT_EVENT.CODE             IS '事件代码，如 HR_HIGH、SPO2_LOW、SOS、FALL、LOW_BATTERY';
COMMENT ON COLUMN ALERT_EVENT.CATEGORY         IS '大屏六类：SOS FALL HEART_RATE BLOOD_PRESSURE SPO2 TEMPERATURE；其余 OTHER（设备事件）';
COMMENT ON COLUMN ALERT_EVENT.SEVERITY         IS '1 提示 / 2 一般 / 3 严重';
COMMENT ON COLUMN ALERT_EVENT.VAL_TEXT         IS '第一次触发时的值，如 132 或 152/98';
COMMENT ON COLUMN ALERT_EVENT.RULE_GROUP       IS '判断体征越界时用的岗位类别；设备报警为空';
COMMENT ON COLUMN ALERT_EVENT.OCCURRED_AT      IS '第一次发生';
COMMENT ON COLUMN ALERT_EVENT.LAST_OCCURRED_AT IS '最近一次发生（去重期间更新）';
COMMENT ON COLUMN ALERT_EVENT.OCCUR_COUNT      IS '去重期间发生的次数';

CREATE INDEX IX_ALERT_EVENT_TIME     ON ALERT_EVENT (OCCURRED_AT);
CREATE INDEX IX_ALERT_EVENT_CARD     ON ALERT_EVENT (CARD_CODE, OCCURRED_AT);
CREATE INDEX IX_ALERT_EVENT_CATEGORY ON ALERT_EVENT (CATEGORY, OCCURRED_AT);

CREATE TABLE WATCH_LIST (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY,
  CARD_CODE   VARCHAR2(17 CHAR) NOT NULL,
  LIST_TYPE   VARCHAR2(10 CHAR) NOT NULL,
  NOTE        VARCHAR2(200 CHAR),
  EXPIRE_DATE DATE,
  ADDED_BY    VARCHAR2(50 CHAR) NOT NULL,
  ADDED_AT    TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0) NOT NULL,
  CONSTRAINT PK_WATCH_LIST PRIMARY KEY (ID),
  CONSTRAINT UK_WATCH_LIST UNIQUE (CARD_CODE, LIST_TYPE),
  CONSTRAINT CK_WATCH_LIST_TYPE CHECK (LIST_TYPE IN ('KEY', 'TODAY'))
);

COMMENT ON TABLE  WATCH_LIST             IS '重点监护、今日关注名单（只靠人工加入和移除）';
COMMENT ON COLUMN WATCH_LIST.LIST_TYPE   IS 'KEY 重点监护 / TODAY 今日关注';
COMMENT ON COLUMN WATCH_LIST.EXPIRE_DATE IS 'TODAY 类型当天有效，过了这天自动失效';
